# Generated by Django 5.1.4 on 2026-03-10 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_solicitud_asesor_alter_solicitud_estado'),
        ('xcore_consumo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuracionagenciacanal',
            options={'verbose_name': 'Configuración agencia canal', 'verbose_name_plural': 'Configuraciones agencia canal'},
        ),
        migrations.AlterModelOptions(
            name='configuraciongastosfamiliares',
            options={'verbose_name': 'Configuración gastos familiares', 'verbose_name_plural': 'Configuraciones gastos familiares'},
        ),
        migrations.AlterModelOptions(
            name='configuracionregresion',
            options={'verbose_name': 'Configuración regresión', 'verbose_name_plural': 'Configuraciones regresión'},
        ),
        migrations.AlterModelOptions(
            name='solicitudconsumo',
            options={'verbose_name': 'Solicitud consumo', 'verbose_name_plural': 'Solicitudes consumo'},
        ),
        migrations.AlterModelOptions(
            name='tasainteresconsumo',
            options={'verbose_name': 'Tasa de interés consumo', 'verbose_name_plural': 'Tasas de interés consumo'},
        ),
        migrations.AlterField(
            model_name='solicitudconsumo',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('OTP_PENDIENTE', 'OTP pendiente'), ('OTP_VALIDADA', 'OTP validada'), ('CONSENTIMIENTO_PENDIENTE', 'Consentimiento pendiente'), ('CONSENTIMIENTO_FIRMADO', 'Consentimiento firmado'), ('CORE_CONSULTADO', 'Core consultado'), ('FORMULARIO_XCORE_OK', 'Formulario guardado'), ('PROCESANDO', 'Procesando'), ('FINALIZADO', 'Finalizado'), ('ERROR', 'Error')], default='OTP_PENDIENTE', max_length=24),
        ),
        migrations.CreateModel(
            name='OtpChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canal', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], default='SMS', max_length=16)),
                ('destino', models.CharField(blank=True, max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('VALIDADA', 'Validada'), ('EXPIRADA', 'Expirada'), ('BLOQUEADA', 'Bloqueada')], default='PENDIENTE', max_length=16)),
                ('enviado_at', models.DateTimeField(blank=True, null=True)),
                ('expira_at', models.DateTimeField(blank=True, null=True)),
                ('verificado_at', models.DateTimeField(blank=True, null=True)),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('max_intentos', models.PositiveSmallIntegerField(default=3)),
                ('ultimo_error', models.CharField(blank=True, max_length=255)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_challenge', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'OTP de solicitud',
                'verbose_name_plural': 'OTPs de solicitud',
            },
        ),
        migrations.CreateModel(
            name='ConsentimientoConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='2026.03', max_length=32)),
                ('aceptado', models.BooleanField(default=True)),
                ('firmado', models.BooleanField(default=True)),
                ('canal', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email')], default='SMS', max_length=16)),
                ('fecha_aceptacion', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('text_snapshot', models.TextField()),
                ('text_hash', models.CharField(max_length=128)),
                ('tipo_firma', models.CharField(default='ACEPTACION_OTP', max_length=32)),
                ('evidencia', models.JSONField(blank=True, default=dict)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consentimiento_consumo', to='solicitudes.solicitud')),
                ('otp', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consentimientos', to='xcore_consumo.otpchallenge')),
            ],
            options={
                'verbose_name': 'Consentimiento consumo',
                'verbose_name_plural': 'Consentimientos consumo',
            },
        ),
    ]
