# Generated by Django 5.1.4 on 2026-03-26 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xcore_consumo", "0004_consultaasociadointento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpchallenge",
            name="estado",
            field=models.CharField(
                choices=[
                    ("PENDIENTE", "Pendiente"),
                    ("ENVIADA", "Enviada"),
                    ("VALIDADA", "Validada"),
                    ("EXPIRADA", "Expirada"),
                    ("BLOQUEADA", "Bloqueada"),
                    ("ERROR_ENVIO", "Error de envio"),
                    ("CANCELADA", "Cancelada"),
                ],
                default="PENDIENTE",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="otpchallenge",
            name="solicitud",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="otp_challenges",
                to="solicitudes.solicitud",
            ),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="blocked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="destination_full_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="destination_masked",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="otp_code_encrypted",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="otp_hash",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="otp_masked",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="provider",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="transaction_uuid",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="validation_result",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="verification_check_sid",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="otpchallenge",
            name="verification_sid",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="consentimientoconsumo",
            name="otp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consentimientos",
                to="xcore_consumo.otpchallenge",
            ),
        ),
        migrations.AddField(
            model_name="consentimientoconsumo",
            name="pdf_consentimiento",
            field=models.FileField(blank=True, upload_to="consentimientos/"),
        ),
    ]
