# Generated by Django 5.1.4 on 2026-03-09 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo_identificacion', models.CharField(choices=[('CC', 'Cedula de ciudadania'), ('CE', 'Cedula de extranjeria'), ('TI', 'Tarjeta de identidad'), ('PAS', 'Pasaporte')], max_length=8)),
                ('numero_identificacion', models.CharField(max_length=32)),
                ('primer_apellido', models.CharField(max_length=80)),
                ('fecha_expedicion', models.DateField()),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Solicitante',
                'verbose_name_plural': 'Solicitantes',
                'ordering': ('-created_at',),
                'unique_together': {('tipo_identificacion', 'numero_identificacion')},
            },
        ),
    ]
