# Generated by Django 5.1.4 on 2026-03-10 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilAsesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('ASESOR', 'Asesor'), ('SUPERVISOR', 'Supervisor'), ('ADMIN', 'Administrador')], default='ASESOR', max_length=16)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_asesor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil asesor',
                'verbose_name_plural': 'Perfiles asesores',
            },
        ),
    ]
