# Generated by Django 5.1.4 on 2026-03-09 21:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero_solicitud', models.CharField(blank=True, max_length=32, unique=True)),
                ('estado', models.CharField(choices=[('INICIADA', 'Iniciada'), ('AUTORIZADA', 'Autorizada'), ('PRESELECTA_OK', 'Preselecta OK'), ('HISTORIAL_OK', 'Historial OK'), ('ENVIADA_XCORE', 'Enviada a XCORE'), ('FINALIZADA', 'Finalizada'), ('ERROR', 'Error')], default='INICIADA', max_length=24)),
                ('paso_actual', models.CharField(default='formulario', max_length=32)),
                ('producto', models.CharField(default='CONSUMO', max_length=32)),
                ('monto_solicitado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('plazo_solicitado', models.PositiveSmallIntegerField(default=24)),
                ('metadatos', models.JSONField(blank=True, default=dict)),
                ('ultimo_error', models.TextField(blank=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='usuarios.solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
                'ordering': ('-created_at',),
            },
        ),
    ]
