# Generated by Django 5.1.4 on 2026-03-10 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='asesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_consumo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('INICIADA', 'Iniciada'), ('AUTORIZADA', 'Autorizada'), ('PRESELECTA_OK', 'Preselecta OK'), ('HISTORIAL_OK', 'Historial OK'), ('ENVIADA_XCORE', 'Enviada a XCORE'), ('FINALIZADA', 'Finalizada'), ('OTP_PENDIENTE', 'OTP pendiente'), ('OTP_VALIDADA', 'OTP validada'), ('CONSENTIMIENTO_PENDIENTE', 'Consentimiento pendiente'), ('CONSENTIMIENTO_FIRMADO', 'Consentimiento firmado'), ('CORE_CONSULTADO', 'Core consultado'), ('FORMULARIO_XCORE_OK', 'Formulario XCORE OK'), ('PROCESANDO', 'Procesando'), ('ERROR', 'Error')], default='INICIADA', max_length=24),
        ),
    ]
