# Generated by Django 5.1.4 on 2026-03-09 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=120)),
                ('level', models.CharField(choices=[('INFO', 'Informacion'), ('WARNING', 'Advertencia'), ('ERROR', 'Error')], default='INFO', max_length=16)),
                ('actor', models.CharField(blank=True, max_length=120)),
                ('request_id', models.CharField(blank=True, max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('solicitud', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditoria',
                'ordering': ('-created_at',),
            },
        ),
    ]
