# Generated by Django 5.1.4 on 2026-03-09 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resultado', models.CharField(choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('REVISION', 'Revision')], max_length=16)),
                ('mensaje', models.CharField(max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('plazo_aprobado', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tasa_interes', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_final', to='solicitudes.solicitud')),
            ],
            options={
                'verbose_name': 'Decision final',
                'verbose_name_plural': 'Decisiones finales',
            },
        ),
    ]
