# Generated by Django 5.1.4 on 2026-03-09 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoLegal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('codigo', models.SlugField(max_length=64, unique=True)),
                ('tipo_documento', models.CharField(choices=[('DATOS', 'Tratamiento de datos'), ('CENTRALES', 'Consulta centrales'), ('TERMINOS', 'Terminos y condiciones')], max_length=16)),
                ('titulo', models.CharField(max_length=180)),
                ('descripcion', models.TextField()),
                ('version', models.CharField(default='1.0', max_length=16)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Documento legal',
                'verbose_name_plural': 'Documentos legales',
                'ordering': ('orden', 'titulo'),
            },
        ),
        migrations.CreateModel(
            name='AceptacionDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aceptado', models.BooleanField(default=True)),
                ('fecha_aceptacion', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceptaciones_documento', to='solicitudes.solicitud')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aceptaciones', to='documentos.documentolegal')),
            ],
            options={
                'verbose_name': 'Aceptacion de documento',
                'verbose_name_plural': 'Aceptaciones de documento',
                'ordering': ('-fecha_aceptacion',),
                'unique_together': {('solicitud', 'documento')},
            },
        ),
    ]
