# Generated by Django 5.1.4 on 2026-03-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aceptaciondocumento',
            name='llego_al_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aceptaciondocumento',
            name='visualizacion_segundos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
